### ISSUE TITLE
Code review Feedback 10-01-2025

### ISSUE THREAD

**Issue by Patrickkhr** [Patrickkhr/release-candidate#30]
### Link element

- Link compontent 
    - Aria-label weg halen
    - Form Aria-label weg halen

### CSS
- @Media "screen" is niet nodig.

### Javascript
```js
.hider.hidden = true;
openmenubtn.hidden = false;
```
### & Nesten binnen de elementen
Probeer je css goed onderhoudbaar te houden door te nesten

``` css
a {
  text-decoration: none;
  &:hover {
  text-decoration: dotted;
}

```

### Tests
- Browser test versie vermelden
- Goed ook mobile devices getest

### Custom properties
- Op elke selector kan je custom properties zetten
- :Root = custom properties afleren
